### ISSUE TITLE
Preparazione del materiale grafico

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#10]
Grafiche necessarie per:
- [x] #11 
- [x] #14
- [x] facebook post
- [x] copertina youtube (1920x1080)
- [x] [open graph](https://www.opengraph.xyz/url/https%3A%2F%2Fods2022.opendatasicilia.it/) (1200 x 630)
- [x] eventbrite (2160 x 1080)

**Comment by aborruso** [comment]
@dennisangemi appena puoi, metti i vettoriali dell'anno scorso nella cartella [risorse/raw](https://github.com/opendatasicilia/ods2022/tree/main/risorse/raw)?

Grazie

**Comment by dennisangemi** [comment]
Fatto @aborruso https://github.com/opendatasicilia/ods2022/commit/a76a2639d7817572bc3c415e77c233ecfa737d8a, grazie a te per aver attivato il dominio di terzo livello

**Comment by dennisangemi** [comment]
L'anno scorso abbiamo preferito una base **dark**. Per far finta di cambiare potremmo pensare di fare qualcosa di **light** (con altri colori) mantenendo gli stessi pallocchi.

Il [file ](https://github.com/opendatasicilia/ods2022/commit/a76a2639d7817572bc3c415e77c233ecfa737d8a) che ho caricato è un `svg` ma il background non è trasparente. Appena ho un po' di tempo preparo una versione senza sfondo che abbia solo il contorno della regione e i pallocchi

**Comment by angelogulina** [comment]
Gentilmente @dennisangemi mi ha delegato questo lavoro (o parte).

@aborruso, la _due date_ è?

**Comment by dennisangemi** [comment]
**proposta color palette**
- `#264653`
- `#2A9D8F`

**Comment by angelogulina** [comment]
> Se ci fosse qualcosa di base per venerdì 8 sarebbe ideale.

Ottimo, @aborruso, grazie.

(PS: purtroppo non ho un ❤️ con cui farlo. Però posso farlo col 🧠 e con le ✊  _ciao, ciao_)

![](https://64.media.tumblr.com/e1a827ebcdc190b1f6bb0ee6de452d75/eaea1bd6eb73f6f8-95/s540x810/24b18157a9ddbd36c324a112edca2dedea8d5925.gif)

**Comment by angelogulina** [comment]
Ciao OpenDatar*.

Ecco qui la direzione grafica che suggerirei per quest'anno. Un richiamo ai '90, colori vivi, accattivanti, accesi. Un po' di auto-ironia. Questa è una prima iterazione, quindi **non è la versione finale**.

La versione con emoji è giusto una variazione per attirare i giovani (ad es. @aborruso). La versione `1` prevede la possibilità di affiancare altri loghi (ad es. UniCT?).

Per piacere indicate feedback come segue:

- 1️⃣ per versione 1
- 2️⃣ per versione 2
- ✊ per versione 1 e 2
- ⬇️ per nessuna versione

Sono graditi commenti. Soprattuto se ci sono info aggiuntive che riteniamo opportuno inserire (ad es., luogo? remoto/non remoto?).

Grazie!

| 1| 2
|-|-|
|![Event Photo Copy 3](https://user-images.githubusercontent.com/4223655/178140207-c1ea43ec-63d8-4df0-88d5-533a4c8f5c72.png)|![Event Photo Copy 4](https://user-images.githubusercontent.com/4223655/178140203-343a09ab-31cc-4b72-9470-318f2bb5d25f.png)

Chiaramente, non poteva mancare la versione in _cörsivœ_:

|CÖRSIVŒ|
|-|
|![Event Photo Copy 5](https://user-images.githubusercontent.com/4223655/178140548-0e90ef76-2bb5-4c32-b1f6-e0a192855bab.png)|

**Comment by gbvitrano** [comment]
voto per versione 1 :-)

**Comment by dennisangemi** [comment]
> voto 1️⃣ per versione 1 :-)

Anche io sono della stessa opinione di Gianni! Grazie @angelogulina, sono bellissime

**Comment by gabacode** [comment]
Anch'io voto 1️⃣
Spaccano, mi piacciono tantissimo :)

**Comment by dtaibi** [comment]
Grazie Angelo! 

Voto 1️⃣

  Davide

**Comment by aborruso** [comment]
✊ per versione 1 e 2

Grazie mille @angelogulina

**Comment by pigreco** [comment]
voto per versione CÖRSIVŒ

**Comment by angelogulina** [comment]
Ciao @dennisangemi – mi pare che il file si comporti bene su diverse piattaforme. Completo le cose che mancano in lista, o va bene così?

**Comment by dennisangemi** [comment]
Ciao @angelogulina e grazie per quanto fatto. Confermo che sembra essere tutto ok su facebook, twitter, telegram e eventbrite. Rimarrebbe da preparare la copertina per youtube ma non è necessario che sia pronta adesso

p.s.
se hai un po' di tempo libero, potresti dare un'occhiata al design del sito #11 ? (io non so intervenire per migliorare il tutto). Senza premura.

Grazie!
