### ISSUE TITLE
pulizia repo

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#13]
Qualcuno per favore si potrebbe occupare di fare una pulizia del repo?

Penserei di eliminare:
- folder [regia](https://github.com/opendatasicilia/ods2022/tree/main/regia)
- file [indiceODS2021.md](https://github.com/opendatasicilia/ods2022/blob/main/indiceODS2021.md)

Penserei di modificare:
- folder [script](https://github.com/opendatasicilia/ods2022/tree/main/script) potremmo lascirla magari per twittare i contenuti del prossimo raduno ma diamo una ripulita a [lista.csv](https://github.com/opendatasicilia/ods2022/blob/main/script/lista.csv) ?

Che ne dite? Per caso sono file che servono?

**Comment by aborruso** [comment]
Caro @dennisangemi c'è tanta roba in più, e si può rimuovere.

Però non ha impatto con l'uso principale del repo, ovvero fare da source al rendering del sito nuovo.

Ho cancellato regia e script.

**Comment by dennisangemi** [comment]
Grazie mille @aborruso . Chiudo
