### ISSUE TITLE
Argomentare "dati e potere"

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#16]
Credo sia necessario scrivere due righe su ciò che si intende per "dati e potere". 

Serve sper:
- aggiungere informazioni al sito e dare forma più consistente al raduno (vedi #11 );
- indirizzare @angelogulina  (vedi #10);
- la presentazione del raduno da inviare ad unict (vedi #9 )

L'anno scorso si era scelto "il valore dei dati" e si era argomentato così:

> Il raduno Open Data Sicilia del 2021 ha come obiettivo quello di fare emergere il valore dei dati. Spesso il motore delle idee e dei progetti che hanno a che fare con i dati, che le nostre comunità portano avanti, è la constatazione che qualcosa - in questo contesto - non funzioni bene o per nulla. È certamente un meccanismo utile, che aiuta a cambiare le cose, che spinge a non demordere, ma che con il passare del tempo restituisce la sensazione di un sistema che non evolve. In questo raduno 2021, invece, vogliamo partire dai dati come fonte di conoscenza, curiosità, entusiasmo. 
> 
> Vogliamo partire dai dati e dal loro valore valore informativo / decisionale / democratico (basti pensare al potere dei dati aperti in tempi critici come quelli di una pandemia mondiale); valore economico (open innovation non è solo una buzzword); valore educativo e ricreativo (perché, diciamolo pure, i dati sono anche e soprattutto divertenti).

Sto assegnando al comitato scientifico ;) ma ovviamente la community fornirà supporto/suggerimenti/commenti

**Comment by angelogulina** [comment]
@gpirrotta e @dataibi, qualche aggiornamento rispetto a questo?

**Comment by dennisangemi** [comment]
@angelogulina in chat è stato inviato questo testo di presentazione: https://docs.google.com/document/d/1QpjHmueNZBRAAycLSxyLvlo0VBCkLl-TAsoWNMGAnl0/edit?usp=sharing

**Comment by dennisangemi** [comment]
È stato fatto qui https://docs.google.com/document/d/1QpjHmueNZBRAAycLSxyLvlo0VBCkLl-TAsoWNMGAnl0/edit . Grazie mille a tutte le persone che hanno contribuito @picomiles @gpirrotta @dataibi @dtaibi @pcmasuzzo @angelogulina (perdonatemi se dimentico qualcuno!)

Chiudo questa con molta soddisfazione!
