### ISSUE TITLE
eventbrite

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#18]
Ciao @nelsonmau , il testo di presentazione del raduno è finalmente pronto. Ti chiederei per favore di fare queste modifiche all'evento di eventbrite:

- **Titolo**: #ODS2022 | Dati e Potere
- **Location**: Catania (e non online. In seguito verrà specificato con dettaglio il luogo preciso)
- **Orario**: dalle 09:00 del 30 settembre alle 18:30 del 1 ottobre
- **Descrizione breve**: Il raduno Open Data Sicilia del 2022 ha l'obiettivo di analizzare la relazione che intercorre tra i dati e il potere.
- **Descrizione long**: “Dati e Potere” è il tema del raduno di quest’anno. Che ci piaccia o meno, i dati sono ovunque. Raccogliamo e utilizziamo i dati ogni volta che guardiamo il nostro orologio fitness per vedere quanti passi abbiamo fatto. Ma non solo, i dati sono uno strumento importante per le  pubbliche amministrazioni per prendere decisioni che hanno a che fare con la nostra vita di tutti i giorni. Ancora, sempre più aziende, al giorno d’oggi, usano dati di ogni natura per scegliere i candidati e le candidate per le loro posizioni di lavoro e i loro profili.
È sempre più evidente che disporre di dati (soprattutto di qualità) costituisce una forma di detenzione del potere. Ecco perché il raduno Open Data Sicilia del 2022 ha come obiettivo quello di analizzare la relazione che intercorre tra i dati e il potere. È un argomento vasto, complesso e di non facile sintesi. Se vuoi ricevere maggiori informazioni visita il sito https://ods2022.opendatasicilia.it

Per quanto riguarda l'immagine di copertina per adesso possiamo lasciarla così, al massimo la modifichiamo in seguito!

p.s. 
attualmente nello slug di questo url https://www.eventbrite.it/e/biglietti-ods2022-il-raduno-2021-di-open-data-sicilia-385755183137 si legge "2021". C'è modo di modificarlo?

grazie grazie grazie

**Comment by nelsonmau** [comment]
check please https://www.eventbrite.it/e/biglietti-ods2022-dati-e-potere-il-raduno-2022-di-open-data-sicilia-385755183137

**Comment by dennisangemi** [comment]
@nelsonmau check passato con successo. Grazie mille!

**Comment by nelsonmau** [comment]
chiudi la issue allora! tocca a te, avendola aperta tu! :-) baci!
