### ISSUE TITLE
[form] modificare link informativa

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#19]
Ciao @gpirrotta , attualmente il link all'informativa sul trattamento dei dati porta l'utente ad effettuare un download automatico del documento. Se invece usiamo il link di seguito https://ods2022.opendatasicilia.it/assets/docs/informativa-trattamento-dati.pdf il documento si aprirà più comodamente nel viewer del browser. Ti chiederei quindi di modificare l'url; non è una cosa urgente nè tantomeno importantissima quindi no rush

p.s.
sorry per il link che ti avevo fornito qualche giorno fa ma ho notato questo piccolo dettaglio proprio adesso

**Comment by gpirrotta** [comment]
Aggiornato

**Comment by dennisangemi** [comment]
Grazie @gpirrotta
