### ISSUE TITLE
[website] pulsanti social

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#20]
Ciao @gbvitrano , per favore potresti occuparti di aggiornare i pulsanti social? Credo sia necessario un cambio di colore e un check degli url ai quali i pulsanti puntano. Senza premura ;) Grazie! #11

**Comment by gbvitrano** [comment]
Corretto, adesso al passaggio del mouse il colore di sfondo delle icone social è il `#eb6067`

**Comment by dennisangemi** [comment]
Grazie Gianni, scusami per l'equivoco: io intendevo queste barra qui 
![image](https://user-images.githubusercontent.com/77018886/179739060-4fa81400-5f02-4840-b856-531cb3763fb1.png)

Le renderei rossa `#eb6067` con icone bianche ma non riesco a trovare il codice da modificare. Sono una frana ;)

**Comment by dennisangemi** [comment]
Grazie mille @gbvitrano ! Anche secondo me quella barra è superflua (io personalmente non uso quasi mai quei buttons) però se volete la possiamo lasciare. Parliamone!

**Comment by gbvitrano** [comment]
Pulsanti social disattivati :-)

**Comment by dennisangemi** [comment]
Grazie @gbvitrano e @aborruso ! Chiudo
