### ISSUE TITLE
transfer ownership

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#22]
Abbiamo un paio di documenti google sparsi ovunque. Conviene organizzarli tutti dentro un'unica folder condivisa.
Di seguito riporto i link dei docs e gli/le attuali proprietari/e a cui chiederei per favore di traferire la proprietà all'account opendatasicilia@gmail.com . (Per traferire la proprietà sarà necessario rendere opendatasicilia@gmail.com prima editor e poi proprietario dalla scheda di condivisione)

- [x] [📄 ODS2022 - log riunioni](https://docs.google.com/document/d/1BoVDuaRL4yI7OTm7ktBTsZKU5e0nKedMDn4T957z4M0/edit#) (owner: @pcmasuzzo )
- [x] [📄 ODS2022 - call for proposal & topics](https://docs.google.com/document/d/191iRun2wohbGLmpdDK_gl0p0e_l1Dw2z5qHmAYAI2uY/edit?usp=sharing) (owner: @gpirrotta )
- [x] [📄 presentazione ODS2022 - dati e potere](https://docs.google.com/document/d/1QpjHmueNZBRAAycLSxyLvlo0VBCkLl-TAsoWNMGAnl0/edit?pli=1)  (owner: @gpirrotta )
- [x] [📄 ODS2022 - richiesta locali unict](https://docs.google.com/document/d/1wM_kCQFfsiXTxp3cjn-ZoAnKAfxmBbyYe1ygy-TbtIU/edit) (owner: @dennisangemi )
- [ ] [📄 ODS2022 - Informativa trattamento dei dati personali](https://docs.google.com/document/d/1D4K8ae92eWbiJKtxOw-ycsDPC2lo7l0pCwMwz4u1cy4/edit) (owner: @cirospat )
- [x] [ODS2022 - passaparola](https://docs.google.com/spreadsheets/d/1FOt60jTTodYQ4fJfbLZK_4B3UfiaCghe2Z_5x0DOvos/edit#gid=0) (owner: @dennisangemi )
- [x] [📄 ODS2022 - possibili partnership raduno](https://docs.google.com/document/d/1wbPyGLkYYFz7Gym0b4rprbXL-x88K930CrbW9UxTDTk/edit?usp=sharing) (owner: @dennisangemi )
- [ ] form contributi (owner: @gpirrotta )
- [ ] form workshop (owner: @gpirrotta )

Per favore flaggate a proprietà trasferita. Grazie!

**Comment by aborruso** [comment]
Qui una cartella condivisa con proprietario opendatasicilia@gmail.com e con accesso soltanto riservato al gruppo operativo:
<https://drive.google.com/drive/folders/14DCNJtEbBeB5aqouxlflPE_N2-fiGl-a?usp=sharing>

**Comment by pcmasuzzo** [comment]
Ho spostato il log riunioni nella cartella nuova.
