### ISSUE TITLE
Menu: si vede male a certe risoluzioni

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/ods2022#24]
Buongiorno,
se provate a ridimensionare la finestra, noterete che a certe risoluzioni si vede male.

Sotto un esempio

![image](https://user-images.githubusercontent.com/30607/180231902-695acb46-1007-483e-8cc2-9c2c56b630ba.png)

**Comment by dennisangemi** [comment]
D'accordo con te @aborruso , io purtroppo non so occuparmene

**Comment by dennisangemi** [comment]
> Buongiorno :-) Dennis c'è il link del template originale? 

https://preview.uideck.com/items/grand/

**Comment by gbvitrano** [comment]
così è se vi piace...
![2022-07-22_11h40_27](https://user-images.githubusercontent.com/20488693/180412638-5996fdb0-fec8-4c00-913b-a1b96417eaea.png)
![2022-07-22_11h43_50](https://user-images.githubusercontent.com/20488693/180412729-745b4cf6-7831-49d4-be5b-1b39070bcda8.png)

**Comment by aborruso** [comment]
Mi sembra che hai risolto.
Per me ok.

**Comment by gbvitrano** [comment]
Ho riadattato l'immagine di sfondo, aggiungendo una piccola parte in alto, ho cambiato colore di sfondo al menù quando è a riposo ed infine ho modificato 2 parametri nel css. il tutto è già on line
