### ISSUE TITLE
[privacy] numero telefono

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#25]
Rimuovere numero di telefono di Nelson (io posso occuparmene tra 5 giorni, se qualcuno riesce a farlo prima è il benvenuto)

**Comment by dennisangemi** [comment]
Grazie @aborruso ! Quand'è tutto fatto per favore sostituisci questo file in questa posizione? Grazie https://github.com/opendatasicilia/ods2022/blob/main/assets/docs/informativa-trattamento-dati.pdf

**Comment by aborruso** [comment]
> Grazie @aborruso ! Quand'è tutto fatto per favore sostituisci questo file in questa posizione? Grazie https://github.com/opendatasicilia/ods2022/blob/main/assets/docs/informativa-trattamento-dati.pdf

Questo URL fa da source del link nel form? Se lo sostituisco, viene quindi risolto tutto?

**Comment by dennisangemi** [comment]
> Questo URL fa da source del link nel form? Se lo sostituisco, viene quindi risolto tutto?

Esattamente
