### ISSUE TITLE
Copertina YT

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#29]
Ciao @angelogulina, so che in questi giorni sei impegnato. Riusciresti a partorire una copertina per la diretta di yt (1920x1080)? Immagino che la deadline sia circa una settimana prima del 30. @aborruso altre indicazioni?

**Comment by aborruso** [comment]
No.

Direi che la tua proposta è corretta.

Grazie

**Comment by dennisangemi** [comment]
ping @angelogulina
