### ISSUE TITLE
Inviare epistola a partecipanti

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#32]
A seguito di #31 sarebbe necessario inviare l'epistola alle persone iscritte e ai/alle moderatori/ici.

@nelsonmau te ne potresti occupare tu che se non ricordo male hai curato le comunicazioni lato eventbrite?

**Comment by dennisangemi** [comment]
Ciao @nelsonmau, l'epistola è stata pubblicata qui https://docs.google.com/document/d/1-Is-4aWc2mvR06srrxcLpam4piud4RE-480zrJMkJyk/edit?usp=sharing per favore potresti inviarla agli/lle iscritti/e (con un minimo di introduzione, se necessario) così come concordato con Oriana? Grazie

**Comment by dennisangemi** [comment]
@pcmasuzzo forse è il caso di individuare dei trigger warning? Ci dai una mano su questo fronte?

**Comment by pcmasuzzo** [comment]
> @pcmasuzzo forse è il caso di individuare dei trigger warning? Ci dai una mano su questo fronte?

Sì. Direi di mettere all'inizio del messaggio:

**TW morte, lutto, malattia**

@nelsonmau ci pensi tu please. Grazie.

**Comment by nelsonmau** [comment]
bozza schedulata per il 29/9/2022 alle 21:15
il TW non lo mettiamo, ne ho parlato con oriana
[la bozza è questa](https://mailchi.mp/eed44745549c/ods2022-epistola-di-oriana-persico-e-salvatore-iaconesi)

**Comment by dennisangemi** [comment]
Ciao @nelsonmau, grazie mi sembra perfetta. L'unica cosa che ti faccio notare è che la parola "sociale" è ripetuta due volte. Grazie!

**Comment by nelsonmau** [comment]
fatto tnx

**Comment by dennisangemi** [comment]
Grazie a te @nelsonmau
