### ISSUE TITLE
Individuare moderatori/ci

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#34]
Sarebbe necessario individuare dei/lle moderatori/ci. Magari ne scegliamo 1 ogni ogni panel?

Di seguito una tabella riassuntiva (in aggiornamento)

Panel | Moderatore/ice
--- | ---
Monitoraggio | 
Ambiente e territorio |
Partecipazione | Nino Galante @picomiles 
Data Literacy | Paola Masuzzo @pcmasuzzo 
DATUR, IL DATO È VITA | Andrea Borruso @aborruso 
SANITÀ |
CORPORATE |
OPEN DATA E PA |
COVID | Dennis Angemi (?) @dennisangemi 

cc @aborruso @nelsonmau @pcmasuzzo @dtaibi @gpirrotta @cirospat @picomiles

**Comment by picomiles** [comment]
Io potrei occuparmi del panel sulla democrazia partecipata

**Comment by pcmasuzzo** [comment]
Io mi offro per la data literacy, ma in realtà se serve faccio la qualunque.

**Comment by dennisangemi** [comment]
Grazie @pcmasuzzo @picomiles, ho aggiunto una tabella nel primo commento di questa issue e ho inserito i vostri nomi.

**Comment by dennisangemi** [comment]
Io potrei occuparmi di moderare sessione covid (mi sento abbastanza a mio agio) ma se si offre qualcun altro/a mi tiro indietro senza problemi.

Quoto Paola quando scrive
> ma in realtà se serve faccio la qualunque.

**Comment by pcmasuzzo** [comment]
**Mi sono presa delle libertà.
Ditemi che ne pensate.**

Panel | Moderatore/ice
--- | ---
Monitoraggio | Giovanni Pirrotta @gpirrotta 
Ambiente e territorio | Davide Taibi @dataibi 
Partecipazione | Nino Galante @picomiles 
Data Literacy | Paola Masuzzo @pcmasuzzo 
DATUR, IL DATO È VITA | Andrea Borruso @aborruso 
SANITÀ | Angelo Gulina @angelogulina 
CORPORATE | Paola Masuzzo @pcmasuzzo (perché c'e' Corsato)
OPEN DATA E PA | Andrea Borruso @aborruso 
COVID | Dennis Angemi @dennisangemi

**Comment by dtaibi** [comment]
Per me va bene, posso portare la parrucca :-))

  Davide

**Comment by angelogulina** [comment]
![](https://c.tenor.com/BP70qe8X0J8AAAAC/crycat-crying-cat.gif)

**Comment by pigreco** [comment]
Purtroppo devo saltare ods2022, è un periodo molto pieno per me.

saluti
