### ISSUE TITLE
Gestione spazi & talk

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#38]
Buongiorno, vi lascio un paio di domande che mi hanno accompagnato durante la notte ;)

1. Lo/a speaker parlerà in piedi?
2. Dove sta il/la moderatore/ice? Dove sta il/la timekeeper? Nelle sedie della prima fila oppure attorno ad un tavolo?
3. Avremo la necessità di un tavolo per @aborruso e udatinos?
4. Dove sarà collocato il pc che utilizzeremo per presentare? Lo lasciamo in regia e utilizziamo uno di quei puntatori laser/cambia slide?
5. Chi darà il benvenuto a tutti/e e introdurrà Francesca Fedeli?

Sforziamoci di arrivare a delle conclusioni il prima possibile così da lasciare tutto pronto e non toglierci la vita il giorno prima del raduno. 

cc @aborruso @nelsonmau @pcmasuzzo @dtaibi @gpirrotta @cirospat @picomiles

**Comment by pcmasuzzo** [comment]
1. Le speaker parlano in piedi.
2. Chi modera e chi tiene il tempo si siedono in prima fila.
3. Un tavolo no, ma possiamo spostare due sedie - direi di metterlo nella nostra lista e guardarci giovedì sera.
4. Non lo so - lascio la parola ad altri.
5. Non lo so - posso farlo io ma non mi sono occupata del raduno tanto quanto l'anno scorso, quindi non mi va di prendermi questo ruolo prezioso. Lo posso fare, se serve, ma non devo assolutamente. Potrebbe @aborruso, o chiunque, really.

My two cents.

**Comment by dennisangemi** [comment]
Grazie @pcmasuzzo
