### ISSUE TITLE
marcatori di capitolo video youtube 2022-09-30

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/ods2022#41]
🔽🔽https://ods2022.opendatasicilia.it/🔽🔽

00:00:00 | inizio registrazione
00:01:00 | Intro Francesco Fedeli
00:03:33 | saluti da Andrea Borruso
00:04:24 | Francesca Fedeli
00:33:09 | Angelo Gulina e Dennis Angemi - 	indecis.it: uno strumento per un voto consapevole
00:49:57 | Vincenzo Savarino - Gestione di dati non open : un approccio user-centrico per i dati personali
01:09:16 | Maurizio Napolitano - I dati AGCOM del pluralismo politico sociale in televisione
01:30:20 | Marco Montanari, Lucia Marsicano - Mappare il passato con dati aperti: una riflessione sul passato dei dati
01:51:32 | Gabriele Arcangelo Scalici - 	MareSì: navigare in dati aperti
02:14:09 | Rosario La Spina - 	Open Data al comune di Messina
02:37:07 | Medea Ferrigno - La mappatura di comunità come strumento di empowerment territoriale
02:57:12 | Alessandra De Renzis, Davide Bruno - Open Toscana - Open Data PNRR
03:14:48 | Giuseppe D'Avella, Francesco Saija - Il progetto Spendiamoli Insieme - Dati sulla democrazia partecipata in Sicilia
03:32:09 | Benedetta Tonnini - Insegnare la data literacy nelle scuole e università europee
03:47:10 | Annalaura Cannavò - Dataviz: raccontare la complessità
04:02:10 | PAUSA PRANZO
05:03:33 | Openantani
05:08:40 | Paola Bommarito - Udatinos.eu Ricordo di Salvatore Iaconesi
05:56:18 | Sonia Montegiove, Chiara Lalli - Mai Dati: perché aprire i dati sulla 194 (e non solo)?
06:15:57 | Maghweb, campagna www noneunveleno it - Diritti, contraccezione d'emergenza, salute sessuale e riproduttiva
06:31:12 | Luca Corsato - 	Fix heritage persistently: Ricevi NFT per il tuo sostegno al patrimonio culturale e sociale
06:51:15 | Stefano Borzì - UNICT DATA - Manipolare ed affinare dati pubblici
07:08:25 | Mario Restuccia - L'Open Data in Francia e data.gouv.fr
07:27:28 | Morena Ragone - Le licenze per i dati aperti dopo le nuove Linee Guida AgID
07:47:29 | Giada Maria Politi - ASOC Pozzillo in Progress
07:58:41 | Aldo Maria Bracco - 	Dati covid e controlli di qualità
08:23:34 | Francesco Branda - How the Pandemic Emphasized the Importance of Real-World Data
08:43:52 | Luigi Tomaselli - Anomalie dei dati pandemici della sola Regione Sicilia
09:06:42 | Luca Naso - Progetto GAIA: un laboratorio condiviso per le comunità emergenti
09:34:00 | Giovanni Pirrotta - Regalo sul CAD

**Comment by pigreco** [comment]
00:00:00 | inizio registrazione
00:01:00 | Intro Francesco Fedeli - Welcome ODS
00:03:33 | saluti da Andrea Borruso
00:04:24 | Francesca Fedeli - Fondazione Fightthestroke
Monitoraggio
00:33:09 | Angelo Gulina e Dennis Angemi - 	indecis.it: uno strumento per un voto consapevole
00:49:57 | Vincenzo Savarino - Gestione di dati non open : un approccio user-centrico per i dati personali
01:09:16 | Maurizio Napolitano - I dati AGCOM del pluralismo politico sociale in televisione
Ambiente e territorio
01:30:20 | Marco Montanari, Lucia Marsicano - Mappare il passato con dati aperti: una riflessione sul passato dei dati
01:51:32 | Gabriele Arcangelo Scalici - 	MareSì: navigare in dati aperti
02:14:09 | Rosario La Spina - 	Open Data al comune di Messina
Partecipazione
02:37:07 | Medea Ferrigno - La mappatura di comunità come strumento di empowerment territoriale
02:57:12 | Alessandra De Renzis, Davide Bruno - Open Toscana - Open Data PNRR
03:14:48 | Giuseppe D'Avella, Francesco Saija - Il progetto Spendiamoli Insieme - Dati sulla democrazia partecipata in Sicilia
Data Literacy
03:32:09 | Benedetta Tonnini - Insegnare la data literacy nelle scuole e università europee
03:47:10 | Annalaura Cannavò - Dataviz: raccontare la complessità
04:02:10 | PAUSA PRANZO
05:03:33 | Openantani
05:08:40 | Paola Bommarito - Udatinos.eu Ricordo di Salvatore Iaconesi
SANITÀ
05:56:18 | Sonia Montegiove, Chiara Lalli - Mai Dati: perché aprire i dati sulla 194 (e non solo)?
06:15:57 | Maghweb, campagna www noneunveleno it - Diritti, contraccezione d'emergenza, salute sessuale e riproduttiva
CORPORATE
06:31:12 | Luca Corsato - 	Fix heritage persistently: Ricevi NFT per il tuo sostegno al patrimonio culturale e sociale
06:51:15 | Stefano Borzì - UNICT DATA - Manipolare ed affinare dati pubblici
OPEN DATA E PA
07:08:25 | Mario Restuccia - L'Open Data in Francia e data.gouv.fr
07:27:28 | Morena Ragone - Le licenze per i dati aperti dopo le nuove Linee Guida AgID
07:47:29 | Giada Maria Politi - ASOC Pozzillo in Progress
COVID
07:58:41 | Aldo Maria Bracco - 	Dati covid e controlli di qualità
08:23:34 | Francesco Branda - How the Pandemic Emphasized the Importance of Real-World Data
08:43:52 | Luigi Tomaselli - Anomalie dei dati pandemici della sola Regione Sicilia
09:06:42 | Luca Naso - Progetto GAIA: un laboratorio condiviso per le comunità emergenti
🎵🎵🎵🎵
09:34:00 | Giovanni Pirrotta - Regalo sul CAD

**Comment by dennisangemi** [comment]
Grazie mille @pigreco !

Chiederei a @aborruso di aggiungere i marcatori nella live yt così come piace a google, grazie!

**Comment by aborruso** [comment]
Caro @pigreco, grazie grazie grazie.

Inseriti
