### ISSUE TITLE
form contributi & formazione

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/ods2022#8]
Ciao @gpirrotta , ti assegno questa issue così come concordato durante l'ultima call.

Sarebbe necessario preparare
- [x] form talk
- [x] form workshop

Grazie!

**Comment by gpirrotta** [comment]
Creato il [form](https://forms.gle/muf15adzZ2BthVHs5) per i contributi del workshop.

**Comment by dennisangemi** [comment]
Ciao @gpirrotta, l'informativa privacy è pronta: Ciro e Mario hanno fatto un lavoro straordinario (e in pochissimo tempo!). Potresti inserire le seguenti informazioni ai moduli? Grazie

- Dichiara di aver preso visione dell'informativa al link https://github.com/opendatasicilia/ods2022/raw/main/assets/docs/informativa-trattamento-dati.pdf fornita ai sensi degli art. 13-14 del GDPR 2016/679

e.g.
![image](https://user-images.githubusercontent.com/77018886/179266809-e7fb848c-bbb6-477e-8b4f-cf434696a14a.png)

- Spuntando il seguente checkbox si autorizza altresì la comunità Open Data Sicilia a diffondere il materiale fotografico e videografico relativo all’intervento di cui sopra tramite i canali di comunicazione che verranno reputati più opportuni (e.g. YouTube, Twitter, Facebook)

**Comment by dennisangemi** [comment]
Ciao @gpirrotta che ne dici di rendere questo campo una "scelta multipla"? ([form workshop](https://forms.gle/muf15adzZ2BthVHs5))
![image](https://user-images.githubusercontent.com/77018886/179358506-cc537b58-96e3-41a6-8a44-3e76357b3f68.png)

**Comment by gpirrotta** [comment]
> Ciao @gpirrotta che ne dici di rendere questo campo una "scelta multipla"? ([form workshop](https://forms.gle/muf15adzZ2BthVHs5)) ![image](https://user-images.githubusercontent.com/77018886/179358506-cc537b58-96e3-41a6-8a44-3e76357b3f68.png)

Ne avevamo parlato con @dataibi e avevamo deciso di lasciarcelo indicare direttamente dal contributor.

**Comment by gpirrotta** [comment]
Entrambi i form riportano adesso il link all'informativa e il consenso obbligatorio.

**Comment by dennisangemi** [comment]
> Entrambi i form riportano adesso il link all'informativa e il consenso obbligatorio.

Grazie mille Giovanni, mancherebbe un altro checkbox "Spuntando il seguente checkbox si autorizza altresì la comunità Open Data Sicilia a diffondere il materiale fotografico e videografico relativo all’intervento di cui sopra tramite i canali di comunicazione che verranno reputati più opportuni (e.g. YouTube, Twitter, Facebook)"

**Comment by dennisangemi** [comment]
Ciao @gpirrotta , nel form dei workshop manca il campo relativo alla durata stimata oppure si è scelto volontariamente di non inserirlo?

**Comment by gpirrotta** [comment]
> Ciao @gpirrotta , nel form dei workshop manca il campo relativo alla durata stimata oppure si è scelto volontariamente di non inserirlo?

Inserito, grazie per la segnalazione.

**Comment by gpirrotta** [comment]
> > Entrambi i form riportano adesso il link all'informativa e il consenso obbligatorio.
> 
> Grazie mille Giovanni, mancherebbe un altro checkbox "Spuntando il seguente checkbox si autorizza altresì la comunità Open Data Sicilia a diffondere il materiale fotografico e videografico relativo all’intervento di cui sopra tramite i canali di comunicazione che verranno reputati più opportuni (e.g. YouTube, Twitter, Facebook)"

Inserito in entrambi i form.

**Comment by dennisangemi** [comment]
Tutto perfetto! Grazie mille @gpirrotta . Chiudo ;)
